# Generated by Django 6.0 on 2025-12-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_galleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Gallery',
        ),
    ]
